name: DPO
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.10.13
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - accelerate==0.27.2
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.3.0
      - appdirs==1.4.4
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - beartype==0.14.1
      - blis==0.7.11
      - cachetools==5.3.3
      - catalogue==2.0.10
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpathlib==0.16.0
      - confection==0.1.4
      - contourpy==1.2.0
      - cycler==0.12.1
      - cymem==2.0.8
      - datasets==2.14.7
      - decorator==5.1.1
      - dill==0.3.7
      - docker-pycreds==0.4.0
      - einops==0.7.0
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - fancy-einsum==0.0.3
      - filelock==3.13.1
      - fonttools==4.49.0
      - frozenlist==1.4.1
      - fsspec==2023.10.0
      - gitdb==4.0.11
      - gitpython==3.1.42
      - google-api-core==2.17.1
      - google-api-python-client==2.108.0
      - google-auth==2.28.2
      - google-auth-httplib2==0.2.0
      - googleapis-common-protos==1.62.0
      - h11==0.14.0
      - httpcore==1.0.5
      - httplib2==0.22.0
      - httpx==0.27.0
      - huggingface-hub==0.23.4
      - idna==3.6
      - iniconfig==2.0.0
      - inquirerpy==0.3.4
      - ipdb==0.13.13
      - ipython==8.22.2
      - jaxtyping==0.2.28
      - jedi==0.19.1
      - jinja2==3.1.3
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - langcodes==3.4.0
      - language-data==1.2.0
      - marisa-trie==1.1.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.3
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.15
      - murmurhash==1.0.10
      - networkx==3.2.1
      - nlp==0.4.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.99
      - nvidia-nvtx-cu12==12.1.105
      - ollama==0.1.8
      - packaging==23.2
      - pandas==2.2.1
      - parso==0.8.3
      - pexpect==4.9.0
      - pfzy==0.3.4
      - pillow==10.2.0
      - pluggy==1.4.0
      - preshed==3.0.9
      - prompt-toolkit==3.0.43
      - protobuf==4.25.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==15.0.1
      - pyarrow-hotfix==0.6
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - pygments==2.17.2
      - pyparsing==3.1.2
      - pytest==8.1.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - regex==2023.12.25
      - requests==2.31.0
      - rich==13.7.1
      - rsa==4.9
      - safetensors==0.4.2
      - scikit-learn==1.4.1.post1
      - scipy==1.13.0
      - seaborn==0.13.1
      - sentry-sdk==1.41.0
      - setproctitle==1.3.3
      - six==1.16.0
      - smart-open==6.4.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - spacy==3.7.4
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - stack-data==0.6.3
      - sympy==1.12
      - tabulate==0.9.0
      - thinc==8.2.3
      - threadpoolctl==3.4.0
      - tokenizers==0.19.1
      - tomli==2.0.1
      - torch==2.2.1
      - torchaudio==2.2.1
      - torchvision==0.17.1
      - tqdm==4.65.0
      - traitlets==5.14.1
      - transformer-lens==1.12.0
      - transformers==4.42.3
      - triton==2.2.0
      - typeguard==2.13.3
      - typer==0.9.4
      - typing-extensions==4.10.0
      - tzdata==2024.1
      - uritemplate==4.1.1
      - urllib3==2.2.1
      - wandb==0.16.4
      - wasabi==1.1.2
      - wcwidth==0.2.13
      - weasel==0.3.4
      - xxhash==3.4.1
      - yarl==1.9.4